const mongoose = require("mongoose");

const InsightSchema = new mongoose.Schema({
  // Primary Identifiers for UI lookup
  cnrNumber: { type: String, required: true, unique: true, index: true },
  lawyerId: { type: String, index: true },
  
  // Analytics (Generated by your script)
  totalHearings: { type: Number, default: 0 },
  lastStage: { type: String, default: "Pending" },
  pendencyDays: { type: Number, default: 0 },
  isDelayed: { type: Boolean, default: false },
  
  // Lawyer-Specific UI content (Not from Excel)
  privateNotes: { type: String, default: "" }, 
  reminders: [{
    text: String,
    dateTime: Date,
    completed: { type: Boolean, default: false }
  }],
  
  // Custom UI helpers
  statusColor: { type: String }
}, { 
  // CRITICAL: strict: false allows all Excel columns (judgeName, policeStation, etc.) 
  // to be saved and sent to the UI even if they aren't defined above.
  strict: false, 
  timestamps: true 
});

module.exports = mongoose.model("Insight", InsightSchema);